name: paip
description: 拍拍应用
publish_to: 'none' # 不发布到 pub.dev

version: 1.0.0+1  # 版本号(1.0.0)和构建号(+1)

environment:
  sdk: '>=3.1.1 <4.0.0' # dart sdk 版本

dependencies: # 运行时依赖
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2 # iOS风格图标包
  http: ^1.1.0

dev_dependencies: # 开发时依赖
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0 # Flutter代码规范检查工具


flutter:

  uses-material-design: true # 使用Material Design设计风格

  assets: # 资源文件
    - assets/images/lake.jpg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
