name: paip
description: 拍拍应用
publish_to: "none" # 不发布到 pub.dev

version: 1.0.0+1 # 版本号(1.0.0)和构建号(+1)

environment:
  sdk: ">=3.1.1 <4.0.0" # dart sdk 版本

dependencies: # 运行时依赖
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2 # iOS风格图标包
  http: ^1.1.0

dev_dependencies: # 开发时依赖
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0 # Flutter代码规范检查工具

flutter:
  uses-material-design: true # 使用Material Design设计风格

  assets: # 资源文件
    - assets/images/
    - assets/images/fruit/
